codecov:
  token: 0aa5a6c3-d2ca-46c4-8c1f-0b1646a75e04
  notify:
    wait_for_ci: true

coverage:
  status:
    project:
      default: false  # disable the default status that measures entire project
      tests:
        paths: "tests/"
        target: 100%
      source:
        paths: "world_bank_data/"
        target: 90%
        threshold': 1%