dist: xenial   # required for Python >= 3.7
language: python
python:
  - "3.6"
  - "3.7"
  - "2.7"
  - "3.5"
  - "3.8"
install:
  # command to install dependencies
  - pip install -r requirements-dev.txt
  - pip install -r requirements.txt
before_script:
  # stop the build if there are Python syntax errors or undefined names
  - flake8 . --count --select=E901,E999,F821,F822,F823 --show-source --statistics
  # exit-zero treats all errors as warnings.  The GitHub editor is 127 chars wide
  - flake8 . --count --exit-zero --max-complexity=10 --statistics
  # follow pep8
  - flake8 world_bank_data tests
script:
  - coverage run --source=. -m py.test
after_success:
  - coverage report -m
  - codecov
