name: world-bank-data
channels:
  - defaults
  - conda-forge
dependencies:
  # dependencies
  - pandas
  - requests
  - cachetools
  # tests
  - pytest
  - pytest-cov
  - pytest-xdist
  # pre-commits
  - pre-commit
  # build
  - hatch
  # Jupyter
  - plotly
  - jupytext
  - jupyter
